### PR TITLE
[SYCL][Graph] Add error checking to make_edge

### LINKED ISSUE #94: Implement error checking from `make_edge()`
Our graphs specification defines the following conditions deriving from `make_edge()`

*  queue is recording commands to the graph object.
* if `src` or `dest` are not valid nodes assigned to the graph object.
* if `src` and `dest` are the same node.
* cycle discovered on finalization.

We should implement checks for these in the code, and test the exceptions are thrown.

### PR DESCRIPTION
**Pull request by Bensuo**
- make_edge now checks for cycles
- no_cycle_check property can now be passed to skip them
- Various other error checks in make_edge
- Generic depth first search mechanism added to graph_impl
- New e2e tests for cycle checks
- Unit tests for other basic errors

Closes #94

### CODE REVIEW

File: sycl/source/detail/graph_impl.cpp [hunk 1]
```diff
@@ -226,6 +228,133 @@ bool graph_impl::clearQueues() {
...
+  auto CheckForNodes = [&](std::shared_ptr<node_impl> &Node,
+                           std::deque<std::shared_ptr<node_impl>> &) {
+    if (Node == Src) {
+      SrcFound = true;
+    }
+    if (Node == Dest) {
+      DestFound = true;
+    }
+    return SrcFound && DestFound;
+  };
```
Comment (mfrancepillois) [inline sycl/source/detail/graph_impl.cpp:330]: If we want to keep the undefined behaviour for the "finalize" step as mentioned in the specification. We could check if Node is already present in "NodeStack" (second param) to break the recursive search if the graph includes a cycle.

File: sycl/source/detail/graph_impl.cpp [hunk 2]
```diff
@@ -226,6 +228,133 @@ bool graph_impl::clearQueues() {
...
+                          "Src must be a node inside the graph.");
+  }
+  if (!DestFound) {
+    throw sycl::exception(make_error_code(sycl::errc::invalid),
+                          "Dest must be a node inside the graph.");
+  }
+
+  // We need to add the edges first before checking for cycles
+  Src->registerSuccessor(Dest,
+                         Src); // register successor
```
Comment (mfrancepillois) [inline sycl/source/detail/graph_impl.cpp]: It might be relevant checking if the edge already exists between these two nodes before adding it again?

**Review by mfrancepillois — APPROVED** [review]
It might be worth adding a Unitest checking the structure of the graph (added edges), especially if a cycle is created by make_edge.

File: sycl/source/detail/graph_impl.cpp (hunk 1 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp:330]: I'm not sure I understand what you mean, do you mean we could combine the searches and just check for both presence of nodes and cycles? That seems possible to me. 

If that's what you mean though I don't understand what that has to do with preserving the graph with cycles until `finalize()`. To do that we would still need to modify the behaviour for these cases specifically which doesn't seem worthwhile to me.

File: sycl/source/detail/graph_impl.cpp (hunk 2 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: Yes that's a sensible idea, in practice I don't think having duplicate edges affects anything but it would be better if it was a no-op.

Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: I've modified `registerSuccessor/Predecessor()` to return early if the Node is already in the respective list.

File: sycl/source/detail/graph_impl.cpp (hunk 1 above)
Comment (mfrancepillois) [reply sycl/source/detail/graph_impl.cpp:330]: In fact, I made this comment before I understood the relevance of offering the no-cycle-check feature.
With the current implementation a cycle in the graph could result in an "infinite" recursive loop.
Just wanted to point out that this risk could be removed by adding an additional check and break condition using NodeStack (similar to the one you did to check cycles).

File: sycl/test-e2e/Graph/cycle_error.cpp
Comment (EwanC) [inline sycl/test-e2e/Graph/cycle_error.cpp:1]: Could we stick this test in the `Explicit` subdirectory

File: sycl/source/detail/graph_impl.hpp [hunk 3]
```diff
@@ -185,9 +199,14 @@ class graph_impl {
   /// Constructor.
   /// @param SyclContext Context to use for graph.
   /// @param SyclDevice Device to create nodes with.
-  graph_impl(const sycl::context &SyclContext, const sycl::device &SyclDevice)
+  graph_impl(const sycl::context &SyclContext, const sycl::device &SyclDevice,
+             const sycl::property_list &PropList = {})
```
Comment (EwanC) [inline sycl/source/detail/graph_impl.hpp:347]: new doxy comment

File: sycl/source/detail/graph_impl.hpp [hunk 4]
```diff
@@ -51,13 +55,23 @@ class node_impl {
...
   }
 
   /// Add predecessor to the node.
   /// @param Node Node to add as a predecessor.
   void registerPredecessor(const std::shared_ptr<node_impl> &Node) {
+    if (std::find_if(MPredecessors.begin(), MPredecessors.end(),
+                     [&Node](const std::weak_ptr<node_impl> &Ptr) {
+                       return Ptr.lock() == Node;
+                     }) != MPredecessors.end()) {
+      return;
```
Comment (EwanC) [inline sycl/source/detail/graph_impl.hpp:73]: is it worth returning a `bool` here to report whether the node was successfully registered? same for `registerSuccessor`

File: sycl/source/detail/graph_impl.cpp (hunk 2 above)
Comment (EwanC) [inline sycl/source/detail/graph_impl.cpp]: Can we remove this `// register sucessor` comment, it doesn't give the reader any information and messes up the formatting

File: sycl/source/detail/graph_impl.cpp [hunk 5]
```diff
@@ -226,6 +228,133 @@ bool graph_impl::clearQueues() {
...
+/// approach.
+/// @param Node The current node being visited.
+/// @param VisitedNodes A set of unique nodes which have already been visited.
+/// @param NodeStack Stack of nodes which are currently being visited on the
+/// current path through the graph.
+/// @param NodeFunc The function object to be run on each node. A return value
+/// of true indicates the search should be ended immediately and the function
+/// will return.
+/// @return True if the search should end immediately, false if not.
+bool visitNodeDepthFirst(
```
Comment (EwanC) [inline sycl/source/detail/graph_impl.cpp]: can we put this in an anonymous namespace since it's a helper function.

File: sycl/source/detail/graph_impl.cpp [hunk 6]
```diff
@@ -226,6 +228,133 @@ bool graph_impl::clearQueues() {
   return AnyQueuesCleared;
 }
 
+/// Visits a node on the graph and it's successors recursively in a depth-first
+/// approach.
+/// @param Node The current node being visited.
```
Comment (EwanC) [inline sycl/source/detail/graph_impl.cpp]: if we could put `[in],[out], [in,out]` on these param descriptions, it would be helpful for knowing how the references are used.

File: sycl/source/detail/graph_impl.hpp (hunk 4 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.hpp:73]: It could be as a "could be useful in the future" thing, I had added similar returns to adding/removing roots but then removed them as they turned out to not be needed in the end. If you think it's a useful addition I can add them, though I don't think there's any current use for them.

File: sycl/source/detail/graph_impl.cpp (hunk 6 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: Done!

File: sycl/source/detail/graph_impl.cpp (hunk 5 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: Done!

File: sycl/source/detail/graph_impl.cpp (hunk 2 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: Done!

File: sycl/source/detail/graph_impl.hpp (hunk 3 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.hpp:347]: Done!

File: sycl/test-e2e/Graph/cycle_error.cpp
Comment (Bensuo) [reply sycl/test-e2e/Graph/cycle_error.cpp:1]: Done!

File: sycl/source/detail/graph_impl.hpp (hunk 4 above)
Comment (EwanC) [reply sycl/source/detail/graph_impl.hpp:73]: Easy enough to add in the future, so fine to leave out for now

File: sycl/source/detail/graph_impl.cpp [hunk 7]
```diff
@@ -71,6 +73,40 @@ bool checkForRequirement(sycl::detail::AccessorImplHost *Req,
...
+    std::deque<std::shared_ptr<node_impl>> &NodeStack,
+    std::function<bool(std::shared_ptr<node_impl> &,
+                       std::deque<std::shared_ptr<node_impl>> &)>
+        NodeFunc) {
+  auto EarlyReturn = NodeFunc(Node, NodeStack);
+  if (EarlyReturn) {
+    return true;
+  }
+  NodeStack.push_back(Node);
+  Node->MVisited = true;
```
Comment (EwanC) [inline sycl/source/detail/graph_impl.cpp:100]: Where are we changing behaviour based on `MVisited`? I see we initalize it to zero, set it to `true` here, then reset it at the end of `graph_impl::searchDepthFirst`. Wondering if we can remove this variable

File: sycl/source/detail/graph_impl.cpp (hunk 1 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp:330]: OK I think I understand, if the user has disabled cycle checks and introduces a cycle here then the check could potentially end up in an infinite loop. However, I'm reluctant to add error handling for this case since this is undefined behaviour, and would make the search for nodes potentially as expensive or more than the check for cycles with no way to remove that behaviour. Since it is only needed when we're in undefined territory I don't think the tradeoff is worth it there.

**Comment by Bensuo** [comment]
> It might be worth adding a Unitest checking the structure of the graph (added edges), especially if a cycle is created by make_edge.

I've updated the unit tests to check the graph structure before and after adding a cycle which throws and is caught 👍

File: sycl/source/detail/graph_impl.cpp (hunk 7 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp:100]: This is more of a generic thing and is a fairly fundamental component of doing a DFS. It was used originally in the cycle check but that actually required the stack for the current path to function correctly. Conceivably it could be useful for other queries that use a DFS. 

I'd be in favour of keeping it for those reasons. It might also make sense to add an optional post-search (but before the visited status is reset) function which could potentially be useful or more efficient for queries that need it, but I'd probably leave that for if/when we actually need it.

Comment (EwanC) [reply sycl/source/detail/graph_impl.cpp:100]: That makes sense, but would like a comment noting that it's current unused and with that rationale for its existence.

Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp:100]: Done!

**Review by EwanC — APPROVED** [review]

File: sycl/source/detail/graph_impl.cpp [hunk 8]
```diff
@@ -226,6 +262,102 @@ bool graph_impl::clearQueues() {
...
+  }
+  if (!DestFound) {
+    throw sycl::exception(make_error_code(sycl::errc::invalid),
+                          "Dest must be a node inside the graph.");
+  }
+
+  // We need to add the edges first before checking for cycles
+  Src->registerSuccessor(Dest, Src);
+
+  if (!MSkipCycleChecks) {
```
Comment (reble) [inline sycl/source/detail/graph_impl.cpp]: It might make sense to also skip the cycle check if the destination node of `make_edge` has no successors. This covers a common case when a graph is connected with only forward edges, and no cycles are possible.

File: sycl/source/detail/graph_impl.cpp (hunk 1 above)
Comment (mfrancepillois) [reply sycl/source/detail/graph_impl.cpp:330]: Makes sense

File: sycl/source/detail/graph_impl.cpp (hunk 8 above)
Comment (Bensuo) [reply sycl/source/detail/graph_impl.cpp]: Good idea! Done.

**Review by julianmi — APPROVED** [review]
