### PR TITLE
[SYCL][Graph] Query for backend command-buffer support

### LINKED ISSUE #90: Define SYCL_EXT_ONEAPI_GRAPH macro
The vendor macro `SYCL_EXT_ONEAPI_GRAPH` specified by the extension specification is not accessible by the user, which should be defined as `1`.

Seeing ` error: use of undeclared identifier 'SYCL_EXT_ONEAPI_GRAPH'` when trying to use it on sycl-graph-develop.

### PR DESCRIPTION
**Pull request by EwanC**
Rather than the user deciding whether to use the emulation mode or backend command-buffer mode, it is less error-prone to do it programmatically as a user can't select an unsupported config.

This also fixes https://github.com/reble/llvm/issues/90 where currently the `SYCL_EXT_ONEAPI_GRAPH` macro isn't defined when in emulation mode.

Done by using a PI device info query in finalization. This also corresponds to a new UR device info query until the extension mechanism is decided https://github.com/oneapi-src/unified-runtime/pull/458 but will be superceeded by whatever extension reporting mechanism is decided on.

The only PI backend which reports support for command-buffer implementation is Level Zero, the other backends/adapters report no support.

### CODE REVIEW

**Review by julianmi — COMMENTED** [review]
Looks good to me in general. One drawback I see is that this would prevent the explicit use of the emulation mode on L0, right? This might be useful for testing or comparing both approaches.

File: sycl/source/detail/graph_impl.cpp [hunk 1]
```diff
@@ -378,83 +380,96 @@ sycl::event exec_graph_impl::enqueue(
...
-                CommandBuffer, Queue->getHandleRef(), RawEvents.size(),
-                RawEvents.empty() ? nullptr : &RawEvents[0], OutEvent);
-    if (Res != pi_result::PI_SUCCESS) {
-      throw sycl::exception(
-          errc::event, "Failed to enqueue event for command buffer submission");
-    }
-  } else {
-    std::unique_ptr<sycl::detail::CG> CommandGroup =
-        std::make_unique<sycl::detail::CGExecCommandBuffer>(CommandBuffer,
-                                                            MRequirements);
```
Comment (Bensuo) [inline sycl/source/detail/graph_impl.cpp:364]: Minor note for future PRs but I think this blank line here has made the diff for this section quite difficult to parse. I've encountered this issue before and found it can be worth checking for things like this to see if they can be removed to make things easier to review.

File: sycl/source/detail/graph_impl.cpp [hunk 2]
```diff
@@ -378,83 +380,96 @@ sycl::event exec_graph_impl::enqueue(
...
+                                         nullptr /* TODO: Handle KernelBundles
+                                                  */
+                                         ,
+                                         NodeImpl->MKernel,
+                                         NodeImpl->MKernelName,
+                                         NodeImpl->MOSModuleHandle, RawEvents,
+                                         OutEvent,
+                                         nullptr /* TODO: Pass mem allocation
+                                                    func for accessors */
+                                         ,
```
Comment (Bensuo) [inline sycl/source/detail/graph_impl.cpp]: The formatting with these parameter comments seems to have gotten a bit messed up.

**Review by Bensuo — APPROVED** [review]
LGTM

**Comment by EwanC** [comment]
> Looks good to me in general. One drawback I see is that this would prevent the explicit use of the emulation mode on L0, right? This might be useful for testing or comparing both approaches.

Yup, I think an L0 emulation mode still does have some value. I guess we'd want to agree on whether the L0 emulation mode should be exposed to users, or it's just for us developing the code. If emulation mode on L0 is just for our own comparison & testing, then I can add an in source `#ifdef` to force emulation mode that can be changed, and then we recompile. Alternatively, if for an end user forcing of emulation is useful, then I can repurpose the existing CMake/configure option from "enable graphs" to "emulate graph", or something that will force the mode to be emulated.

**Review by reble — APPROVED** [review]
LGTM

File: sycl/source/detail/graph_impl.cpp (hunk 2 above)
Comment (EwanC) [reply sycl/source/detail/graph_impl.cpp]: Manually sorted this out, by moving comments to the line above

File: sycl/source/detail/graph_impl.cpp (hunk 1 above)
Comment (EwanC) [reply sycl/source/detail/graph_impl.cpp:364]: This diff is definitely noisier than I thought it would be. I tried removing the blank line, but didn't seem to help much. I'll bear this in mind to help similar situations in future.

**Comment by EwanC** [comment]
> > Looks good to me in general. One drawback I see is that this would prevent the explicit use of the emulation mode on L0, right? This might be useful for testing or comparing both approaches.
> 
> Yup, I think an L0 emulation mode still does have some value. I guess we'd want to agree on whether the L0 emulation mode should be exposed to users, or it's just for us developing the code. If emulation mode on L0 is just for our own comparison & testing, then I can add an in source `#ifdef` to force emulation mode that can be changed, and then we recompile. Alternatively, if for an end user forcing of emulation is useful, then I can repurpose the existing CMake/configure option from "enable graphs" to "emulate graph", or something that will force the mode to be emulated.

I went with the second approach and added a `FORCE_EMULATION_MODE` define to the top of `graph_impl.cpp`. If a developer flips this from `0` to `1` and recompiles, it will force emulation node for targets with native support, i.e L0 right now.

**Review by julianmi — APPROVED** [review]
