### PR TITLE
[SYCL][Graph] Add exceptions on invalid event and queue usage

### LINKED ISSUE #97: Implement error handling for invalid event/queue usage
Implement the erroneous wait behaviour defined by https://github.com/reble/llvm/pull/78

This includes:

*  Throwing an error on `handler::depends_on()` when an event is passed that doesn't correspond to a node (related to https://github.com/reble/llvm/issues/89)
* Throwing an error when waiting on an event returned from a queue submission recorded to a graph.
* calling `queue::wait()` on a queue in the recording state

### PR DESCRIPTION
**Pull request by Bensuo**
- Throws when waiting on a queue in recording mode.
- Throws when waiting on an event from a graph submission.
- Throws when calling depends_on with an event outside the graph.
- Adds new tests for the exceptions.

Closes #97

### CODE REVIEW

File: sycl/include/sycl/handler.hpp [hunk 1]
```diff
@@ -1526,6 +1526,12 @@ class __SYCL_EXPORT handler {
     setType(detail::CG::CodeplayHostTask);
   }
 
+  /// @brief Get the command graph if any associated with this handler. It can
+  /// come from either the associated queue or from being set explicitly through
+  /// the appropriate constructor.
+  std::shared_ptr<ext::oneapi::experimental::detail::graph_impl>
+  getCommandGraph() const;
+
```
Comment (EwanC) [inline sycl/include/sycl/handler.hpp:1534]: Thankfully this isn't a breaking change, but it is a ABI change. There's a new symbol that needs added to `abi/sycl_symbols_linux.dump`

**Review by EwanC — APPROVED** [review]
LGTM, one abi test that needs updated

File: sycl/include/sycl/handler.hpp (hunk 1 above)
Comment (EwanC) [reply sycl/include/sycl/handler.hpp:1534]: I actually just pushed a fix to this branch quickly, since I have the command-line for generating symbols in my bash history

File: sycl/test-e2e/Graph/invalid_event_wait.cpp [hunk 2]
```diff
@@ -0,0 +1,29 @@
...
+  auto GraphEvent = Queue.submit(
+      [&](handler &CGH) { CGH.single_task<class TestKernel>([=]() {}); });
+
+  Graph.end_recording(Queue);
+
+  try {
+    GraphEvent.wait();
+  } catch (const sycl::exception &e) {
+    assert(e.code() == sycl::errc::invalid);
+  }
```
Comment (mfrancepillois) [inline sycl/test-e2e/Graph/invalid_event_wait.cpp]: You can have silent fail with this test. 
If no exception is thrown the test will pass because we do not enter into the catch branch, while it should fail.

File: sycl/test-e2e/Graph/invalid_queue_wait.cpp [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+  ext::oneapi::experimental::command_graph Graph{Queue.get_context(),
+                                                 Queue.get_device()};
+  Graph.begin_recording(Queue);
+
+  try {
+    Queue.wait();
+  } catch (const sycl::exception &e) {
+    assert(e.code() == sycl::errc::invalid);
+  }
```
Comment (mfrancepillois) [inline sycl/test-e2e/Graph/invalid_queue_wait.cpp]: Same issue of silent fail.

File: sycl/test-e2e/Graph/invalid_depends_on.cpp [hunk 4]
```diff
@@ -0,0 +1,68 @@
...
+
+  // Test that depends_on throws from an event from another graph.
+  try {
+    auto GraphEvent = Queue.submit([&](handler &CGH) {
+      CGH.depends_on(OtherGraphEvent);
+      CGH.single_task<class TestKernel5>([=]() {});
+    });
+  } catch (const sycl::exception &e) {
+    assert(e.code() == sycl::errc::invalid);
+  }
```
Comment (mfrancepillois) [inline sycl/test-e2e/Graph/invalid_depends_on.cpp]: You can have silent fail here
If no exception is thrown the test will pass because we do not enter into the catch branch, while it should fail.

File: sycl/test-e2e/Graph/invalid_depends_on.cpp [hunk 5]
```diff
@@ -0,0 +1,68 @@
...
+  try {
+    Graph.add([&](handler &CGH) {
+      CGH.depends_on(OtherGraphEvent);
+      CGH.single_task<class TestKernel6>([=]() {});
+    });
+  } catch (const sycl::exception &e) {
+    assert(e.code() == sycl::errc::invalid);
+  }
```
Comment (mfrancepillois) [inline sycl/test-e2e/Graph/invalid_depends_on.cpp]: You can have silent fail here
If no exception is thrown the test will pass because we do not enter into the catch branch, while it should fail.

**Review by mfrancepillois — APPROVED** [review]
LGTM, but the tests could be improved to avoid silent failures

File: sycl/test-e2e/Graph/invalid_event_wait.cpp (hunk 2 above)
Comment (Bensuo) [reply sycl/test-e2e/Graph/invalid_event_wait.cpp]: Fixed, thanks!

**Review by julianmi — APPROVED** [review]
LGTM. We could extend the unittests as well to check for the exceptions introduced.
