### PR TITLE
[SYCL] Fix reductions not working inside graph

### LINKED ISSUE #24: Dot product test fails with missing event message
Summary of the issue:

The dot product test in the `sycl-graph-poc-v2` branch currently fails to run correctly, with the following output:
```
die: The host-visible proxy event missing
terminate called without an active exception
```

Summary of findings:

- Issue is caused by the use of the reduction object in the last graph node. This creates a requirement for an auxiliary resource when the command is scheduled.
- When the aux resources are being cleaned up they wait for any command submissions to have finished, however the lazy queue command list is not correctly indicating that it has finished executing and at this point the runtime panics.
- It's unclear whether the command list is notifying correctly and this is just not being reflected in the host visible event associated with the command or if it is failing to notify altogether.
- Making sure that the graph command list correctly notifies the associated event when it is finished should fix the issue, though exactly where that change needs to happen is unclear to me.
- Existing queue mechanisms for resetting and cleaning up command lists may help to avoid code duplication, if they can be used with the separate lazy command list.

### PR DESCRIPTION
**Pull request by Bensuo**
Graph submission now properly creates a host visible event on the command list allowing auxilliary resources to be cleaned up. 
~~Code is taken from `_pi_queue::executeCommandList`, copy pasting a decent amount of code like that is not ideal but there isn't an immediately obvious solution to let us actually use that function when flushing.~~

Updated to remove code duplication, instead relying on the `OKtoBatchCommand` parameter to `executeCommandList` to let us determine when to actually submit the command list and when to block execution.

This will at least make the examples that use reductions run, though it doesn't solve related problems with buffers and other regular operations on the queue.

Closes #24

### CODE REVIEW

**Comment by reble** [comment]
@Bensuo Great! Thanks for fixing that. We should just add a note with a TODO to remove the code duplication.

Now I'm wondering why we should not just call `executeCommandList(CommandList,false,false)` and make sure that we opt in the event creation when in lazy mode? Like:
`if( !Device->useImmediateCommandLists() || Queue->Properties & PI_EXT_ONEAPI_QUEUE_LAZY_EXECUTION ) {`

The idea was to decouple closing and executing the CommandList. But that is not what is happening now.

**Review by reble — APPROVED** [review]

File: sycl/plugins/level_zero/pi_level_zero.cpp [hunk 1]
```diff
@@ -3841,7 +3841,70 @@ pi_result piQueueFlush(pi_queue Queue) {
     // true).
     std::unique_lock<pi_shared_mutex> ContextsLock(
       Queue->Device->Platform->ContextsMutex, std::defer_lock);
-      
+
```
Comment (EwanC) [inline sycl/plugins/level_zero/pi_level_zero.cpp]: Agree that we should add a comment note here that the following code is duplicated

**Review by EwanC — APPROVED** [review]
Nice work figuring this out ⭐ 
Think we should merge this to fix current issues, and then try to rework as Pablo suggests as a follow-up

File: sycl/plugins/level_zero/pi_level_zero.cpp (hunk 1 above)
Comment (Bensuo) [reply sycl/plugins/level_zero/pi_level_zero.cpp]: I've added a comment indicating this!

**Comment by Bensuo** [comment]
> @Bensuo Great! Thanks for fixing that. We should just add a note with a TODO to remove the code duplication.
> 
> Now I'm wondering why we should not just call `executeCommandList(CommandList,false,false)` and make sure that we opt in the event creation when in lazy mode? Like: `if( !Device->useImmediateCommandLists() || Queue->Properties & PI_EXT_ONEAPI_QUEUE_LAZY_EXECUTION ) {`
> 
> The idea was to decouple closing and executing the CommandList. But that is not what is happening now.

So I've been looking into this idea and I think I have something along those lines. I think we only need to modify the initial check in `executeCommandList` to also check if it's allowed to batch. We can somewhat assume that kernels will always be allowed to batch (and thus blocked from executing immediately) so if we're not allowed to batch we allow execution (so it works when called from the flush). It doesn't address any of the additional issues other than reductions and relying on kernels always being allowed to batch could be problematic if that changes in the future. It would remove all the code duplication from flush though.

I'll push it as an update to this PR but can always roll back to the already approved duplication approach if need be.

**Review by EwanC — APPROVED** [review]
